package com.xyh.demo.domain.po;

import com.alibaba.excel.annotation.ExcelIgnore;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ybs_version_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class YbsVersionInfoPo implements Serializable {
    /**
     * Database Column Remarks:
     *   版本id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.id
     *
     * @mbg.generated
     */
//    @ExcelProperty(value = "序号")
    private Long id;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.version
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "版本号",index = 0)
    private String version;

    /**
     * Database Column Remarks:
     *   版本内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.content
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "版本内容",index = 1)
    @ColumnWidth(value = 50)
    private String content;

    /**
     * Database Column Remarks:
     *   渠道编码：ybgj：银保 bxj:保险家 lcjl:理财经理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.channel_code
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "渠道编码",index = 2)
    private String channelCode;

    /**
     * Database Column Remarks:
     *   渠道名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.channel_name
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "渠道名称",index = 3)
    private String channelName;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.create_by
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "创建人",index = 4)
    private String createBy;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.update_by
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private String updateBy;

    /**
     * Database Column Remarks:
     *   是否发布 0：否 1：是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.is_release
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "是否发布",index = 5)
    private Integer isRelease;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.release_date
     *
     * @mbg.generated
     */
    @ExcelProperty(value = "发布时间",index = 6)
    private Date releaseDate;

    /**
     * Database Column Remarks:
     *   生效开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.start_time
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private Date startTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.gmt_create
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.gmt_update
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private Date gmtUpdate;

    /**
     * Database Column Remarks:
     *   是否删除 0：否 1 是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ybs_version_info.del_flag
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    @ExcelIgnore
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", version=").append(version);
        sb.append(", content=").append(content);
        sb.append(", channelCode=").append(channelCode);
        sb.append(", channelName=").append(channelName);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", isRelease=").append(isRelease);
        sb.append(", releaseDate=").append(releaseDate);
        sb.append(", startTime=").append(startTime);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}