package com.xyh.demo.mapper;

import com.xyh.demo.domain.po.YbsVersionInfoPo;
import com.xyh.demo.domain.po.YbsVersionInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YbsVersionInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    long countByExample(YbsVersionInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int deleteByExample(YbsVersionInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int insert(YbsVersionInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int insertSelective(YbsVersionInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    List<YbsVersionInfoPo> selectByExample(YbsVersionInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    YbsVersionInfoPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YbsVersionInfoPo record, @Param("example") YbsVersionInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YbsVersionInfoPo record, @Param("example") YbsVersionInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YbsVersionInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ybs_version_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YbsVersionInfoPo record);
}